In [5]:
import numpy
import copy

def gauss_1(a: 'ndarray', b: 'ndarray', i: 'int', j: 'int'):
    c = numpy.array(a[0].copy())
    k = a[i][j]/a[0][j]
    for p in range(len(c)):
        c[p] *= k
    for p in range(j, len(a[1])):
                   a[i][p] -= c[p]
    b[i] -= k*b[0]
    print(a) #just for now
    
def gauss_2(a: 'ndarray', b: 'ndarray'):
    x = []
    for i in range(len(b-1)):
        x.append([])

        
        
        
        
    return(x)

In [6]:
a = numpy.array([
    [1,2,3,4],
    [3,10,5,7],
    [4,9,21,49],
    [55,24,68,95]
])

lenght = len(b)
b = numpy.array([26,42,49,77])
    
for j in range(0, lenght-1):
    for i in range(j+1, len(a)):
        gauss_1(a, b, i, j)
        

[[ 1  2  3  4]
 [ 0  4 -4 -5]
 [ 4  9 21 49]
 [55 24 68 95]]
[[ 1  2  3  4]
 [ 0  4 -4 -5]
 [ 0  1  9 33]
 [55 24 68 95]]
[[   1    2    3    4]
 [   0    4   -4   -5]
 [   0    1    9   33]
 [   0  -86  -97 -125]]
[[   1    2    3    4]
 [   0    4   -4   -5]
 [   0    0    8   31]
 [   0  -86  -97 -125]]
[[ 1  2  3  4]
 [ 0  4 -4 -5]
 [ 0  0  8 31]
 [ 0  0 32 47]]
[[ 1  2  3  4]
 [ 0  4 -4 -5]
 [ 0  0  8 31]
 [ 0  0  0  5]]
